### ISSUE TITLE
dapple install fails

### ISSUE THREAD

**Issue by stevenh512** [MakerDAO/maker-user#5]
The exact command line from the readme file, `dapple install makeruser 0.1.0` gives me this error:

```
Retrieving makeruser
installing makeruser@0.1.0 from dapphub
Error: No IPFS hash found for makeruser@0.1.0
```

I get similar results if I try `dapple install makeruser 0.1.4` (the version in this project's dappfile) or `dapple install makeruser` (without a version).

```
Retrieving makeruser
installing makeruser@0.1.4 from dapphub
Error: No IPFS hash found for makeruser@0.1.4
```

```
Retrieving makeruser
installing makeruser@latest from dapphub
Error: No IPFS hash found for makeruser@0.0.0
```

I had no problem installing the latest dappsys with `dapple install dappsys 0.1.2` on the same machine, with the same geth nodes (live and morden) and the same ipfs node running. Has this been published to dapphub at all? If not, is it safe to assume that if I want to use this I can just include it as a git submodule?

**Comment by nmushegian** [comment]
Submodules are the most reliable at this point. We might still support git URLs, @mhhf or @ryepdx know where we are in the transition. @mhhf should also know which packages are in the beta registry.

**Comment by mhhf** [comment]
Unfortunately only `dappsys@0.1.2` is in the registry for now. We work hard to provide all packages from the registry. Installing makeruser@0.1.4 should be possible on Monday.

**Comment by stevenh512** [comment]
Thanks. I'm fairly new to Ethereum and don't really have any specific project in mind at the moment, just tinkering with whatever code I can find to try to understand what's possible. Looking forward to seeing more packages in the registry, it'll be nice to be able to use dapple the same way I'd use rubygems or npm.. but for now, submodules will do.
