### ISSUE TITLE
ETH frontend missing

### ISSUE THREAD

**Issue by jorisbontje** [MakerDAO/maker-user#7]
Looking at https://github.com/MakerDAO/maker-user/blob/master/dappfile there are objects defined for `MAR`, `mkr_frontend` and `dai_frontend`; however an `eth_frontend` (or whatever we call the `DSEthToken` instance) appears to be missing. Is there a contract deployed on morden / live for this?

**Comment by nmushegian** [comment]
There is an eth token wrapper registered at "ETH" in maker's token registry. You're right, it may as well be saved to the dappfile. Calling it a frontend would not be accurate, it's a simple standalone contract that just exposes ether as an ERC20 interface.

**Comment by nmushegian** [comment]
https://github.com/nexusdev/dappsys/blob/master/contracts/token/eth_wrapper.sol
